apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: nogitops-e2e
spec:
  replicas: 2
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: invaleed/argo-hello:commitid
        name: demo
        env:
        - name: ENVIRONMENT
          value: e2e
        ports:
        - containerPort: 80
